name: Exercise 3 - Repository Variables

on:
  workflow_dispatch:

jobs:
  use-variable:
    name: Use Repo Variable
    runs-on: ubuntu-latest
    environment: DEVELOPMENT
    
    steps:
      - name: Print variable
        shell: bash
        run: echo "deploying: ${{ vars.SERVICE_NAME }}"
