name: Exercise 3 - Repository Variables

on:
  workflow_dispatch:

jobs:
  deploy:
    name: ğŸ§© Deploy with SERVICE_NAME
    runs-on: ubuntu-latest
    environment: DEVELOPMENT
    steps:
      - name: ğŸ Start Deployment
        shell: bash
        run: |
          echo "deploying: ${{ vars.SERVICE_NAME }}"
